version: '3.8'

services:
  flask-back:
    build: ./back
    container_name: flask-back
    ports:
      - "5000:5000"  # Expose Flask backend on port 8080

  react-frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3001:80"  # React app on port 80 inside, mapped to 3001 on host

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8081:80"  # Nginx listens on port 8081 on the host
    depends_on:
      - flask-back
      - react-frontend
